services:
  db:
    image: postgres
    container_name: lpoo2-postgres-db
    ports:
      - "8081:5432"

    environment:
      POSTGRES_DB: lpoo2database
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
